# Searchable Indian airport-city catalog based on Airports Authority of India
# operational airport and licensed aerodrome lists. This is a destination
# directory, not a claim that every city pair has scheduled service or fare data.
cities:
  - Agartala
  - Agatti
  - Agra
  - Ahmedabad
  - Aizawl
  - Ajmer (Kishangarh)
  - Akola
  - Aligarh
  - Amritsar
  - Aurangabad
  - Ayodhya
  - Bagdogra
  - Bareilly
  - Belagavi
  - Bengaluru
  - Bhavnagar
  - Bhopal
  - Bhubaneswar
  - Bhuj
  - Bidar
  - Bikaner
  - Bilaspur
  - Chandigarh
  - Chennai
  - Coimbatore
  - Cooch Behar
  - Cuddapah
  - Darbhanga
  - Dehradun
  - Deoghar
  - Delhi
  - Dibrugarh
  - Dimapur
  - Diu
  - Durgapur
  - Gaya
  - Goa
  - Gondia
  - Gorakhpur
  - Guwahati
  - Gwalior
  - Hubballi
  - Hyderabad
  - Imphal
  - Indore
  - Itanagar
  - Jabalpur
  - Jaipur
  - Jaisalmer
  - Jammu
  - Jamnagar
  - Jamshedpur
  - Jharsuguda
  - Jodhpur
  - Jorhat
  - Kadapa
  - Kangra
  - Kannur
  - Kanpur
  - Kandla
  - Keshod
  - Khajuraho
  - Kochi
  - Kolhapur
  - Kolkata
  - Kullu
  - Kushinagar
  - Leh
  - Lilabari
  - Lucknow
  - Ludhiana
  - Madurai
  - Mangaluru
  - Mumbai
  - Mysuru
  - Nagpur
  - Nanded
  - Nashik
  - Pantnagar
  - Patna
  - Porbandar
  - Port Blair
  - Prayagraj
  - Puducherry
  - Pune
  - Raipur
  - Rajahmundry
  - Rajkot
  - Ranchi
  - Rupsi
  - Salem
  - Shillong
  - Shimla
  - Shirdi
  - Shravasti
  - Silchar
  - Srinagar
  - Surat
  - Tezu
  - Thiruvananthapuram
  - Thoothukudi
  - Tiruchirappalli
  - Tirupati
  - Udaipur
  - Vadodara
  - Varanasi
  - Vijayawada
  - Visakhapatnam
  - Ziro

# Match commonly used contemporary names to labels in the historical sample.
aliases:
  Bengaluru: Bangalore
  Belagavi: Belgaum
  Cuddapah: Kadapa
  Hubballi: Hubli
  Kochi: Cochin
  Mangaluru: Mangalore
  Mysuru: Mysore
  Prayagraj: Allahabad
  Puducherry: Pondicherry
  Rajahmundry: Rajamundry
  Thoothukudi: Tuticorin
